# Kokoro TTS引擎配置

# 引擎类型
type: kokoro

# 基本设置
lang_code: z  # 中文:'z', 英语:'a'(美式)/'b'(英式), 日语:'j', 法语:'f', 西班牙语:'e', 意大利语:'i', 印地语:'h', 葡萄牙语:'p'
default_voice: zh_f1  # 默认声音ID
speed: 1.0  # 语速倍率，1.0为正常语速

# 自定义声音模型路径（可选）
# voice_tensor_path: /path/to/custom_voice.pt

# 温度设置（控制生成的随机性）
temperature: 0.6
